### ISSUE TITLE
玩家上桌加入游戏有报错

### ISSUE THREAD

**Issue by icedlemon233** [Michael1015198808/mirai-landlord#3]
一发上桌就出现报错，如下
2022-03-03 11:45:24 E/mirai斗地主插件: Exception in coroutine Plugin mirai.landlord of mirai斗地主插件
java.io.IOException: 系统找不到指定的路径。
        at java.base/java.io.WinNTFileSystem.createFileExclusively(Native Method)
        at java.base/java.io.File.createNewFile(File.java:1043)
        at net.mamoe.mirai.console.internal.data.MultiFilePluginDataStorageImpl.getPluginDataFile(MultiFilePluginDataStorageImpl.kt:60)
        at net.mamoe.mirai.console.internal.data.MultiFilePluginDataStorageImpl.load(MultiFilePluginDataStorageImpl.kt:36)
        at net.mamoe.mirai.console.plugin.jvm.AbstractJvmPlugin.reloadPluginData(AbstractJvmPlugin.kt:50)
        at michael.landlord.PluginMain.getPlayerInfo(PluginMain.kt:163)
        at michael.landlord.main.Desk.getPlayerInfo(Desk.kt:755)
        at michael.landlord.main.Desk.playersInfo(Desk.kt:1224)
        at michael.landlord.main.Desk.join(Desk.kt:853)
        at michael.landlord.PluginMain$onEnable$2.invokeSuspend(PluginMain.kt:217)
        at michael.landlord.PluginMain$onEnable$2.invoke(PluginMain.kt)
        at michael.landlord.PluginMain$onEnable$2.invoke(PluginMain.kt)
        at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invokeSuspend(EventChannel.kt:455)
        at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invoke(EventChannel.kt)
        at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invoke(EventChannel.kt)
        at net.mamoe.mirai.internal.event.Handler$onEvent$2.invokeSuspend(InternalEventListeners.kt:50)
        at net.mamoe.mirai.internal.event.Handler$onEvent$2.invoke(InternalEventListeners.kt)
        at net.mamoe.mirai.internal.event.Handler$onEvent$2.invoke(InternalEventListeners.kt)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:165)
        at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
        at net.mamoe.mirai.internal.event.Handler.onEvent(InternalEventListeners.kt:50)
        at net.mamoe.mirai.internal.event.InternalEventListenersKt.process(InternalEventListeners.kt:166)
        at net.mamoe.mirai.internal.event.InternalEventListenersKt.callAndRemoveIfRequired(InternalEventListeners.kt:115)
        at net.mamoe.mirai.internal.event.InternalEventListenersKt$callAndRemoveIfRequired$1.invokeSuspend(InternalEventListeners.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:147)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by Michael1015198808** [comment]
非常抱歉，这个应该是由于代码缺少初始化导致的，你可以试一下在data下斗地主的目录里创建一个叫players的文件夹看看能否解决（如果我没记错应该是mcl目录下的data/mirai-landlord/players），如果确定是这个问题的话我就hot fix一下

**Comment by icedlemon233** [comment]
> 非常抱歉，这个应该是由于代码缺少初始化导致的，你可以试一下在data下斗地主的目录里创建一个叫players的文件夹看看能否解决（如果我没记错应该是mcl目录下的data/mirai-landlord/players），如果确定是这个问题的话我就hot fix一下

好了，现在解决了。目录是 data/mirai.landlord/players
